# Site settings
title: "Sébastien Wieckowski, Ph.D."
author:
  name: "Sébastien Wieckowski"
  email: sbwiecko@gmail.com
description: "Full resume"

# Build settings
plugins:
  - jekyll-relative-links
theme: jekyll-theme-time-machine
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - resume_visual_84.pdf